### ISSUE TITLE
Navbar Responsiveness

### ISSUE THREAD

**Issue by Kevin-Solomon** [Kevin-Solomon/starUI-component-library#15]
## Navbar component lacks responsiveness in screens with width smaller than 380px
![image](https://user-images.githubusercontent.com/80545228/152033879-e093349e-685f-40e7-b7e7-2abc189b919c.png)

**Comment by prtdh** [comment]
hey can u assign this to me? i will fix it

**Comment by Kevin-Solomon** [comment]
> hey can u assign this to me? i will fix it

Hey prtdh, I love your enthusiasm to fix the issue. 
But sadly these were assigned to me by my mentor.
Do you know that you can still contribute to the project after its completion?
